version: '3'

services:

  middleware:
    build: .
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=rest_api.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    links:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - /home/emil/Development/Project_ailo/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379