"""empty message

Revision ID: 0d478b12e2e1
Revises: 162daae1ce2d
Create Date: 2019-05-30 09:53:59.937762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d478b12e2e1'
down_revision = '162daae1ce2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('domain_id', sa.String(length=32), nullable=False),
    sa.Column('datetime_added', sa.DateTime(), nullable=True),
    sa.Column('datetime_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('release', sa.Column('friendly_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'friendly_name')
    op.drop_table('cloud')
    # ### end Alembic commands ###
