"""empty message

Revision ID: 12a9fa82d944
Revises: bdbdaf4378cd
Create Date: 2019-04-22 18:18:30.443483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a9fa82d944'
down_revision = 'bdbdaf4378cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'name')
    # ### end Alembic commands ###
