"""empty message

Revision ID: 5897ab618569
Revises: 88b28aed3acf
Create Date: 2019-04-22 20:25:53.412159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5897ab618569'
down_revision = '88b28aed3acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'release')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('release', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
