"""empty message

Revision ID: 91b6b2e4afa1
Revises: 1b69eb43d002
Create Date: 2019-03-24 16:05:57.585866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b6b2e4afa1'
down_revision = '1b69eb43d002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('release', 'distro_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('release', 'distro_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
