"""empty message

Revision ID: 9390d464bf6c
Revises: 5897ab618569
Create Date: 2019-04-23 11:05:21.524785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9390d464bf6c'
down_revision = '5897ab618569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'archive_filename',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('image', 'archive_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'archive_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('image', 'archive_filename',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
